/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as TruthRouteImport } from './routes/truth'
import { Route as CowIdRouteImport } from './routes/cow.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthRoute = TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => rootRouteImport,
} as any)
const CowIdRoute = CowIdRouteImport.update({
  id: '/cow/$id',
  path: '/cow/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/truth': typeof TruthRoute
  '/cow/$id': typeof CowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/truth': typeof TruthRoute
  '/cow/$id': typeof CowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/truth': typeof TruthRoute
  '/cow/$id': typeof CowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forge' | '/truth' | '/cow/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forge' | '/truth' | '/cow/$id'
  id: '__root__' | '/' | '/forge' | '/truth' | '/cow/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgeRoute: typeof ForgeRoute
  TruthRoute: typeof TruthRoute
  CowIdRoute: typeof CowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth': {
      id: '/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cow/$id': {
      id: '/cow/$id'
      path: '/cow/$id'
      fullPath: '/cow/$id'
      preLoaderRoute: typeof CowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgeRoute: ForgeRoute,
  TruthRoute: TruthRoute,
  CowIdRoute: CowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
