/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TillRouteImport } from './routes/till'
import { Route as TruthRouteImport } from './routes/truth'
import { Route as CowIdRouteImport } from './routes/cow.$id'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TillRoute = TillRouteImport.update({
  id: '/till',
  path: '/till',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthRoute = TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => rootRouteImport,
} as any)
const CowIdRoute = CowIdRouteImport.update({
  id: '/cow/$id',
  path: '/cow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/paid': typeof PaidRoute
  '/shop': typeof ShopRoute
  '/till': typeof TillRoute
  '/truth': typeof TruthRoute
  '/cow/$id': typeof CowIdRoute
  '/s/$id': typeof SIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/paid': typeof PaidRoute
  '/shop': typeof ShopRoute
  '/till': typeof TillRoute
  '/truth': typeof TruthRoute
  '/cow/$id': typeof CowIdRoute
  '/s/$id': typeof SIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forge': typeof ForgeRoute
  '/paid': typeof PaidRoute
  '/shop': typeof ShopRoute
  '/till': typeof TillRoute
  '/truth': typeof TruthRoute
  '/cow/$id': typeof CowIdRoute
  '/s/$id': typeof SIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forge'
    | '/paid'
    | '/shop'
    | '/till'
    | '/truth'
    | '/cow/$id'
    | '/s/$id'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forge'
    | '/paid'
    | '/shop'
    | '/till'
    | '/truth'
    | '/cow/$id'
    | '/s/$id'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/forge'
    | '/paid'
    | '/shop'
    | '/till'
    | '/truth'
    | '/cow/$id'
    | '/s/$id'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgeRoute: typeof ForgeRoute
  PaidRoute: typeof PaidRoute
  ShopRoute: typeof ShopRoute
  TillRoute: typeof TillRoute
  TruthRoute: typeof TruthRoute
  CowIdRoute: typeof CowIdRoute
  SIdRoute: typeof SIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/till': {
      id: '/till'
      path: '/till'
      fullPath: '/till'
      preLoaderRoute: typeof TillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth': {
      id: '/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cow/$id': {
      id: '/cow/$id'
      path: '/cow/$id'
      fullPath: '/cow/$id'
      preLoaderRoute: typeof CowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgeRoute: ForgeRoute,
  PaidRoute: PaidRoute,
  ShopRoute: ShopRoute,
  TillRoute: TillRoute,
  TruthRoute: TruthRoute,
  CowIdRoute: CowIdRoute,
  SIdRoute: SIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
