/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TillRouteImport } from './routes/till'
import { Route as TruthRouteImport } from './routes/truth'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSalesRouteImport } from './routes/api/sales'
import { Route as ApiStallsRouteImport } from './routes/api/stalls'
import { Route as CowIdRouteImport } from './routes/cow.$id'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiDownloadTokenRouteImport } from './routes/api/download.$token'
import { Route as ApiNangoWebhookRouteImport } from './routes/api/nango/webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TillRoute = TillRouteImport.update({
  id: '/till',
  path: '/till',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthRoute = TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesRoute = ApiSalesRouteImport.update({
  id: '/api/sales',
  path: '/api/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStallsRoute = ApiStallsRouteImport.update({
  id: '/api/stalls',
  path: '/api/stalls',
  getParentRoute: () => rootRouteImport,
} as any)
const CowIdRoute = CowIdRouteImport.update({
  id: '/cow/$id',
  path: '/cow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadTokenRoute = ApiDownloadTokenRouteImport.update({
  id: '/api/download/$token',
  path: '/api/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNangoWebhookRoute = ApiNangoWebhookRouteImport.update({
  id: '/api/nango/webhook',
  path: '/api/nango/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/forge': typeof ForgeRoute
  '/paid': typeof PaidRoute
  '/shop': typeof ShopRoute
  '/till': typeof TillRoute
  '/truth': typeof TruthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/stalls': typeof ApiStallsRoute
  '/cow/$id': typeof CowIdRoute
  '/d/$token': typeof DTokenRoute
  '/s/$id': typeof SIdRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/nango/webhook': typeof ApiNangoWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/forge': typeof ForgeRoute
  '/paid': typeof PaidRoute
  '/shop': typeof ShopRoute
  '/till': typeof TillRoute
  '/truth': typeof TruthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/stalls': typeof ApiStallsRoute
  '/cow/$id': typeof CowIdRoute
  '/d/$token': typeof DTokenRoute
  '/s/$id': typeof SIdRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/nango/webhook': typeof ApiNangoWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/forge': typeof ForgeRoute
  '/paid': typeof PaidRoute
  '/shop': typeof ShopRoute
  '/till': typeof TillRoute
  '/truth': typeof TruthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/stalls': typeof ApiStallsRoute
  '/cow/$id': typeof CowIdRoute
  '/d/$token': typeof DTokenRoute
  '/s/$id': typeof SIdRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/nango/webhook': typeof ApiNangoWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deck'
    | '/forge'
    | '/paid'
    | '/shop'
    | '/till'
    | '/truth'
    | '/api/health'
    | '/api/sales'
    | '/api/stalls'
    | '/cow/$id'
    | '/d/$token'
    | '/s/$id'
    | '/api/download/$token'
    | '/api/nango/webhook'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deck'
    | '/forge'
    | '/paid'
    | '/shop'
    | '/till'
    | '/truth'
    | '/api/health'
    | '/api/sales'
    | '/api/stalls'
    | '/cow/$id'
    | '/d/$token'
    | '/s/$id'
    | '/api/download/$token'
    | '/api/nango/webhook'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/deck'
    | '/forge'
    | '/paid'
    | '/shop'
    | '/till'
    | '/truth'
    | '/api/health'
    | '/api/sales'
    | '/api/stalls'
    | '/cow/$id'
    | '/d/$token'
    | '/s/$id'
    | '/api/download/$token'
    | '/api/nango/webhook'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckRoute: typeof DeckRoute
  ForgeRoute: typeof ForgeRoute
  PaidRoute: typeof PaidRoute
  ShopRoute: typeof ShopRoute
  TillRoute: typeof TillRoute
  TruthRoute: typeof TruthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSalesRoute: typeof ApiSalesRoute
  ApiStallsRoute: typeof ApiStallsRoute
  CowIdRoute: typeof CowIdRoute
  DTokenRoute: typeof DTokenRoute
  SIdRoute: typeof SIdRoute
  ApiDownloadTokenRoute: typeof ApiDownloadTokenRoute
  ApiNangoWebhookRoute: typeof ApiNangoWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/till': {
      id: '/till'
      path: '/till'
      fullPath: '/till'
      preLoaderRoute: typeof TillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth': {
      id: '/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales': {
      id: '/api/sales'
      path: '/api/sales'
      fullPath: '/api/sales'
      preLoaderRoute: typeof ApiSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stalls': {
      id: '/api/stalls'
      path: '/api/stalls'
      fullPath: '/api/stalls'
      preLoaderRoute: typeof ApiStallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cow/$id': {
      id: '/cow/$id'
      path: '/cow/$id'
      fullPath: '/cow/$id'
      preLoaderRoute: typeof CowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$token': {
      id: '/api/download/$token'
      path: '/api/download/$token'
      fullPath: '/api/download/$token'
      preLoaderRoute: typeof ApiDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nango/webhook': {
      id: '/api/nango/webhook'
      path: '/api/nango/webhook'
      fullPath: '/api/nango/webhook'
      preLoaderRoute: typeof ApiNangoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckRoute: DeckRoute,
  ForgeRoute: ForgeRoute,
  PaidRoute: PaidRoute,
  ShopRoute: ShopRoute,
  TillRoute: TillRoute,
  TruthRoute: TruthRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSalesRoute: ApiSalesRoute,
  ApiStallsRoute: ApiStallsRoute,
  CowIdRoute: CowIdRoute,
  DTokenRoute: DTokenRoute,
  SIdRoute: SIdRoute,
  ApiDownloadTokenRoute: ApiDownloadTokenRoute,
  ApiNangoWebhookRoute: ApiNangoWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
